<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group( array(
	'key' => 'group_59e63b46ba6c8',
	'title' => 'Location Data',
	'fields' => array(
		array(
			'key' => 'field_59e63b64de299',
			'label' => 'Latitude',
			'name' => 'latitude',
			'type' => 'text',
			'value' => NULL,
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59e63baede29a',
			'label' => 'Longitude',
			'name' => 'longitude',
			'type' => 'text',
			'value' => NULL,
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59e63bbdde29b',
			'label' => 'City',
			'name' => 'city',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59e63bc9de29c',
			'label' => 'State',
			'name' => 'state',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59e63bcede29d',
			'label' => 'Zip',
			'name' => 'zip',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_93jfue8574jiod',
			'label' => 'Street Address',
			'name' => 'street_address',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59e63bdcde29e',
			'label' => 'Full Address',
			'name' => 'full_address',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => 'This field will be used anytime the address needs displayed',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_59e63be6de29f',
			'label' => 'Phone Number',
			'name' => 'phone',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_59e63bf3de2a0',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'email',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_0dofi94n5h674',
			'label' => 'Hide On Site',
			'name' => 'hide_on_site',
			'type' => 'checkbox',
			'value' => NULL,
			'instructions' => 'If this box is checked, this location will not appear throughout the site but will still show on the event calendar as a fileter',
			'required' => 0,
			'choices' => array(
				'true' => 'Yes'
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(),
			'layout' => 'block',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_dmksi41n28da9',
			'label' => 'Hide On Calendar',
			'name' => 'hide_on_calendar',
			'type' => 'checkbox',
			'value' => NULL,
			'instructions' => 'If this box is checked, this location will not appear on the event calendar as a location filter',
			'required' => 0,
			'choices' => array(
				'true' => 'Yes'
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(),
			'layout' => 'block',
			'toggle' => 0,
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'locations',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
) );

endif;

?>
