<?php

acf_add_local_component( 'hero', array(
	'key' => 'group_37ed53c2b9g4a',
	'title' => 'Hero',
	'fields' => array(
		array(
			'key' => 'field_37ed53c2b9g3a',
			'label' => 'Hero Type',
			'name' => 'hero_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'hero-regular' => 'Hero',
				'hero-video' => 'Hero with Video',
				'hero-text' => 'Text Only Hero',
				'hero-nonav' => 'No Nav Hero',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'regular-hero',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_dkv938vdien43',
			'label' => 'Theme',
			'name' => 'hero_theme',
			'type' => 'radio',
			'instructions' => 'Choose between light or dark theme',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_37ed53c2b9g3a',
						'operator' => '==',
						'value' => 'hero-text',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'light' => 'Light',
				'dark' => 'Dark'
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'dark',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_jd92vd74g32vr',
			'label' => 'Replacement Logo',
			'name' => 'replacement_logo',
			'type' => 'image',
			'value' => NULL,
			'instructions' => 'Replacement Logo for no-nav version of hero (regualr site header/nav is hidden)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_37ed53c2b9g3a',
						'operator' => '==',
						'value' => 'hero-nonav',
					),
				),
			),
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_37ed53c2b9g3f',
			'label' => 'Background Image',
			'name' => 'background_image',
			'type' => 'image',
			'value' => NULL,
			'instructions' => 'Image that appears as the background on desktop and mobile if no mobile image is uploaded. For best results the image should be of landscape orientation at least 1800px wide, no more then 2400px wide and at least 400px tall.',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_37ed53c2b9g3a',
						'operator' => '!=',
						'value' => 'hero-text',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '1800',
			'min_height' => '400',
			'min_size' => '',
			'max_width' => '2400',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_vd93vv93039vd',
			'label' => 'Mobile Background Image',
			'name' => 'background_image_mobile',
			'type' => 'image',
			'value' => NULL,
			'instructions' => '(optional) Background image when on Mobile. For best results, the image should be portrait oriented and at least 640px wide, no more then 800px wide and at least 400px tall',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_37ed53c2b9g3a',
						'operator' => '!=',
						'value' => 'hero-text',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '640',
			'min_height' => '400',
			'min_size' => '',
			'max_width' => '800',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_3vd0gd93c5o09',
			'label' => 'Grayscale',
			'name' => 'grayscale',
			'type' => 'checkbox',
			'value' => NULL,
			'instructions' => 'Apply grayscale to background image',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_37ed53c2b9g3a',
						'operator' => '!=',
						'value' => 'hero-text',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'true' => 'Yes'
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(),
			'layout' => 'block',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_37ed53c2b9g3b',
			'label' => 'Pre Title',
			'name' => 'hero_pre_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_37ed53c2b9g3a',
						'operator' => '==',
						'value' => 'hero-search',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_37ed53c2b9g3c',
			'label' => 'Title',
			'name' => 'hero_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_37ed53c2b9g3d',
			'label' => 'Text/Copy',
			'name' => 'hero_copy',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 6,
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_37ed53c2b9g41',
			'label' => 'CTAs',
			'name' => 'hero_ctas',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 2,
			'layout' => 'block',
			'button_label' => 'Add CTA',
			'sub_fields' => array(
				array(
					'key' => 'field_37ed5c2b9g41a',
					'label' => 'Clone',
					'name' => 'clone',
					'type' => 'clone',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'clone' => array(
						0 => 'group_2b5d52c1b8g21',
					),
					'display' => 'seamless',
					'layout' => 'block',
					'prefix_label' => 0,
					'prefix_name' => 1,
				),
			),
		),
		array(
			'key' => 'field_59fc9d049a607',
			'label' => 'Video',
			'name'	=> 'hero_video',
			'type' => 'oembed',
			'instructions' => 'Place in the video embed url',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_37ed53c2b9g3a',
						'operator' => '==',
						'value' => 'hero-video',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
) );
