<?php

acf_add_local_component( 'big-numbers', array(
	'key' => 'group_59f2822f73088',
	'title' => 'Big Numbers',
	'fields' => array (
		array (
			'key' => 'field_59f282a40c466',
			'label' => 'Big Number Item',
			'name' => 'big_number_item',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 3,
			'layout' => 'row',
			'button_label' => 'Add Item',
			'sub_fields' => array (
				array (
					'key' => 'field_59f282b60c467',
					'label' => 'Big Number',
					'name' => 'big_number',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 5,
				),
				array (
					'key' => 'field_59f282c00c468',
					'label' => 'Copy',
					'name' => 'copy',
					'type' => 'textarea',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
			),
		),
	),
	'location' => array (

	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));
