<?php
acf_add_local_component( 'cta', array (
	'key' => 'group_2b5d52c1b8g21',
	'title' => 'CTA',
	'fields' => array (
		array (
			'key' => 'field_2b5d52c1b8g2a',
			'label' => 'CTA Text',
			'name' => 'cta_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_2b5d52c1b8gb5',
			'label' => 'CTA Color',
			'name' => 'cta_color',
			'type' => 'radio',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'white' => 'White',
				'blue' => 'Blue',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'blue',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_2b5d52c1b8g2b',
			'label' => 'Open in new window?',
			'name' => 'cta_new_window',
			'type' => 'radio',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_2b5d52c1b8g2c',
			'label' => 'CTA Type',
			'name' => 'cta_link_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'custom' => 'Custom URL',
				'internal' => 'Internal Page/Post',
				'file' => 'File/Upload',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'custom',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_2b5d52c1b8g2d',
			'label' => 'Custom URL',
			'name' => 'cta_custom_url',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_2b5d52c1b8g2c',
						'operator' => '==',
						'value' => 'custom',
					),
				),
			),
			'wrapper' => array (
				'width' => '70',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_2b5d52c1b8g2e',
			'label' => 'Internal Page/Post',
			'name' => 'cta_internal_url',
			'type' => 'page_link',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_2b5d52c1b8g2c',
						'operator' => '==',
						'value' => 'internal',
					),
				),
			),
			'wrapper' => array (
				'width' => '70',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
				1 => 'post',
			),
			'taxonomy' => array (
			),
			'allow_null' => 0,
			'allow_archives' => 1,
			'multiple' => 0,
		),
		array (
			'key' => 'field_2b5d52c1b8g2f',
			'label' => 'File',
			'name' => 'cta_file_url',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_2b5d52c1b8g2c',
						'operator' => '==',
						'value' => 'file',
					),
				),
			),
			'wrapper' => array (
				'width' => '70',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
	'active' => 0
) );
