<?php
acf_add_local_component( 'workshop', array(
	'key' => 'group_9384nduey1738',
	'title' => 'Workshop',
	'fields' => array(
		array(
			'key' => 'field_5bb2807abf713',
			'label' => 'Position',
			'name' => 'position',
			'type' => 'radio',
			'value' => NULL,
			'instructions' => 'Left or right',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'Left',
				'right' => 'Right',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'left',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_1di348dngy210',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => 'Image must be 1600 X 900 pixels',
			'wrapper' => array(
				'width' => '70',
			),
			'preview_size' => 'medium',
			'mime_types' => '',
			'required' => 1,
			'min_width' => 1600,
			'min_height' => 900,
			'min_size' => '',
			'max_width' => 1600,
			'max_height' => 900,
		),
		array(
			'key' => 'field_5bb29765a6441',
			'label' => 'Main Content',
			'name' => 'main_content',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_304kd8vf723jv',
			'label' => 'Links',
			'name' => 'links',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => 'Add up to 3 links below the main content',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 3,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_1029v8d74h5u3',
					'label' => 'Link URL',
					'name' => 'link_url',
					'type' => 'url',
					'value' => NULL,
					'instructions' => 'URL for the anchor link',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_01lvmfiw93ia8',
					'label' => 'Link Text',
					'name' => 'link_text',
					'type' => 'text',
					'value' => NULL,
					'instructions' => 'Text for the link',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5bb2801fbf712',
			'label' => 'Heading',
			'name' => 'heading',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_19vjufir8th4k',
			'label' => 'Heading Link',
			'name' => 'heading_link',
			'type' => 'url',
			'value' => NULL,
			'instructions' => 'URL for the heading link',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bb280e6bf714',
			'label' => 'Sub-Heading',
			'name' => 'sub-heading',
			'type' => 'text',
			'value' => NULL,
			'instructions' => 'Sub-Heading that appears above the bullet list',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5bb2854eee965',
			'label' => 'List Items',
			'name' => 'list-items',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5bb28579ee966',
					'label' => 'List Item',
					'name' => 'list-item',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5bb28143bf715',
			'label' => 'Workshops',
			'name' => 'workshops',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Workshop',
			'sub_fields' => array(
				array(
					'key' => 'field_5bb281adbf716',
					'label' => 'Icon',
					'name' => 'icon',
					'type' => 'icomoon',
					'value' => NULL,
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'allow_clear' => 0,
				),
				array(
					'key' => 'field_5bb281debf717',
					'label' => 'Tooltip',
					'name' => 'tooltip',
					'type' => 'text',
					'value' => NULL,
					'instructions' => 'The tooltip that display when hovering over the icon',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));
