
<?php

acf_add_local_component( 'latest-news', array(
	'key' => 'group_9304nfjru8475',
	'title' => 'Latest News',
	'fields' => array(
		array(
			'key' => 'field_28jdue73i1k2n4',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_03948vd1e3j92',
			'label' => 'Latest News Type',
			'name' => 'latest_news_types',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'latest-news-regular' => 'Latest News',
				'latest-news-filtered' => 'Latest News Filtered',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'latest-news-regular',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_k3nv83ugn2730',
			'label' => 'Mode',
			'name' => 'mode',
			'type' => 'radio',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'light' => 'Light',
				'dark' => 'Dark',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'dark',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5a14f62d73347',
			'label' => 'Select One Category',
			'name' => 'category',
			'type' => 'taxonomy',
			'value' => NULL,
			'instructions' => 'Display latest news article from this category',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_03948vd1e3j92',
						'operator' => '==',
						'value' => 'latest-news-filtered',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 1,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
) );
