<?php
acf_add_local_component( 'short-newsletter-form', array(
	'key' => 'group_5a29a10230cd4',
	'title' => 'Short Newsletter Form Fields',
	'fields' => array(
		array(
			'key' => 'field_5a29a1111dc30',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'value' => NULL,
			'instructions' => 'This field appears above the form as an h3.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_2918vu419jiq8',
			'label' => 'Sub Title',
			'name' => 'sub_title',
			'type' => 'text',
			'value' => NULL,
			'instructions' => 'This fields only appears on desktop directly below the H3.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));
