<?php
acf_add_local_component( 'two-column-text', array (
	'key' => 'group_59f37e87ead94',
	'title' => 'Two Column Text',
	'fields' => array (
		array (
			'key' => 'field_59f37ea1ss3571c',
			'label' => 'Mode',
			'name' => 'mode',
			'type' => 'radio',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'light' => 'Light',
				'dark' => 'Dark',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'dark',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59f37ebwwwwa3571d',
			'label' => 'Header',
			'name' => 'header',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 0,
		),
	array (
		'key' => 'field_5wwww9f37ed53571b',
		'label' => 'Left Text',
		'name' => 'left_wysiwyg',
		'type' => 'wysiwyg',
		'value' => NULL,
		'instructions' => 'Try to keep the right and left columns the same length',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'tabs' => 'all',
		'toolbar' => 'basic',
		'media_upload' => 0,
		'delay' => 0,
	),
	array (
		'key' => 'field_59f37f0e3wwww571k',
		'label' => 'Right Text',
		'name' => 'right_wysiwyg',
		'type' => 'wysiwyg',
		'value' => NULL,
		'instructions' => 'Try to keep the right and left columns the same length',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
			),
		'default_value' => '',
		'placeholder' => '',
		'maxlength' => '',
		'tabs' => 'all',
		'toolbar' => 'basic',
		'media_upload' => 0,
		'rows' => '',
		'new_lines' => '',
		),
	),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
) );
