<?php

acf_add_local_field_group( array(
	'key' => 'group_94hv8fn4hguro',
	'title' => 'Location Modal',
	'fields' => array(
		array(
			'key' => 'field_d9j4bufyr9384',
			'label' => 'Google Maps API Key',
			'name' => 'google_maps_api_key',
			'type' => 'text',
			'instructions' => 'Input your google maps api key',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_039fjdivue83k',
			'label' => 'Location Modal Heading',
			'name' => 'location_modal_heading',
			'type' => 'text',
			'instructions' => 'This copy will appear on the location modal',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_v0d9sjrieoplk',
			'label' => 'Location Modal Heading',
			'name' => 'location_modal_heading',
			'type' => 'text',
			'instructions' => 'This heading will appear on the location modal',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_v0d9sjrieoplk',
			'label' => 'Location Modal Copy',
			'name' => 'location_modal_copy',
			'type' => 'textarea',
			'instructions' => 'This copy will appear on the location modal',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_93049fheuiwi3',
			'label' => 'Default Location',
			'name' => 'default_location',
			'type' => 'post_object',
			'value' => NULL,
			'instructions' => 'Select a default location',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'locations',
			),
			'taxonomy' => array(),
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'ID',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
) );
